version: "2.1"
services:
  base_rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  service_rabbitmq:
    depends_on:
      - base_rabbitmq
    image: service_rabbitmq
    restart: unless-stopped
    build: rabbitmq/
    ports:
      - "8080:8080"

  service_worker:
    depends_on:
      - base_rabbitmq
    image: service_worker
    restart: unless-stopped
    build: worker/
